// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_Conexao_MYSQL.Data;

#nullable disable

namespace Projeto_Conexao_MYSQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260711172346_CriarTabelaProdutos")]
    partial class CriarTabelaProdutos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Projeto_Conexao_MYSQL.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estoques")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomesProdutos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Precos")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
