name: Deploy SQL Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Executar script no Azure SQL
        uses: azure/sql-action@v2
        with:
          connection-string: "Server=tcp:${{ secrets.AZURE_SERVER }},1433;Initial Catalog=${{ secrets.AZURE_DATABASE }};Persist Security Info=False;User ID=${{ secrets.AZURE_USER }};Password=${{ secrets.AZURE_PASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
          path: './script.sql'
          action: 'execute'
